FROM node:16-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN mkdir -p cache && touch cache/notes.json 

RUN mkdir -p static

COPY static/UploadForm.html static/UploadForm.html

# Install dependencies
COPY package.json .
RUN npm install

# Bundle app source
COPY . .

# Exports
EXPOSE 8000
CMD [ "npm", "run", "start.dev" ]